### ISSUE TITLE
[문의] nested multimodule 질문

### ISSUE THREAD

**Issue by jasone-jaewon** [team-dodn/spring-boot-kotlin-template#10]
지금은 구조상 clients/client-example 하나의 모듈에서 feign 설정을 관리하고 있는데요.
만약에 다른 client가 추가되는 경우에는 어떻게 되는지 궁금합니다.
공통 설정인 clients/common 으로 빼시는지 아니면 clients 모듈에 하위에 src 폴더를 생성해서 진행하시는지 궁금합니다.

제가 테스트 했던 것들 공유드리면 
### clients/common 
이 방식으로 진행하면 각 client들이 common 모듈을 build.gradle에서 implementation으로 가지고 있으니 해결되었습니다.

### clients 하위에 src 생성
이 경우는 자동으로 하위 module에서 dependency를 가져갈 것으로 예상했는데 그렇지 않은 것 같네요.
따로 방법을 찾지 못했습니다.

**Comment by geminiKim** [comment]
우선 방식을 선택한다면 `clients/common` 을 사용해서 처리합니다.

다만, 공통 모듈을 너무 빠르게 추가하지 않는편 입니다.
공통 모듈이 생기고 공통 모듈의 의존이 생기게되면 수정에 의한 사이드이펙트가 전파 될 수 있기 때문입니다.

우선 각 client 모듈에 명시적 중복이 존재하게 유지하면서 운영하다가 정말 공통 사항이 명확해지는 시점에 부분만 추출하여 커먼을 만드는 편입니다.

**Comment by jasone-jaewon** [comment]
답변 너무 감사드립니다.
